# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='PhotoPath',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='PlanName',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='TimeEnd',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='TimeStart',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='dayCount',
        ),
        migrations.RemoveField(
            model_name='tripmain',
            name='DateEnd',
        ),
        migrations.RemoveField(
            model_name='tripmain',
            name='DateStart',
        ),
        migrations.RemoveField(
            model_name='tripmain',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='tripmain',
            name='MainLocation',
        ),
        migrations.RemoveField(
            model_name='tripmain',
            name='TopPhoto',
        ),
        migrations.RemoveField(
            model_name='tripmain',
            name='TotalDay',
        ),
        migrations.AlterField(
            model_name='plan',
            name='Type',
            field=models.CharField(blank=True, choices=[('景點', '景點'), ('住宿', '住宿'), ('用餐', '用餐')], max_length=50),
        ),
    ]
