# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_auto_20160730_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Order',
            field=models.IntegerField(default=0),
        ),
    ]
