# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_plan_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
